AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  servicio-locaciones-java17

  Sample SAM Template for servicio-locaciones-java17
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
Parameters:
  TableName:
    Type: String
    Default: 'book'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'
  TableBooks:
    Type: String
    Default: 'book'
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'
Resources:
  #Service Locations API Gateway
  ServiciosApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: servicios-api-gateway

  BookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BookFunction
      Handler: book.App::handleRequest
      Runtime: java17
      Architectures:
        - arm64
        #  - x86_64
      MemorySize: 512
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /book
            Method: GET
            RestApiId: !Ref ServiciosApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            # TableName: book
            TableName: !Ref TableBooks
        
  # books:
  #   Type: 'AWS::DynamoDB::Table'
  #   Properties:
  #     # TableName: book
  #     TableName: !Ref TableBooks
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "N"
  #     KeySchema:
  #       - AttributeName: "id"
  #         KeyType: HASH
  #     BillingMode: PROVISIONED
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 10
  #       WriteCapacityUnits: 10

Outputs:
  ServiciosApiGateway:
    Description: "API Gateway endpoint URL for Prod stage for Book function"
    Value: !Sub "https://${ServiciosApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/location/"
  BookFunction:
    Description: "Book Lambda Function ARN"
    Value: !GetAtt BookFunction.Arn
  BookFunctionIamRole:
    Description: "Implicit IAM Role created for Book function"
    Value: !GetAtt BookFunctionRole.Arn
